"""
Seed data — 300+ từ vựng tiếng Anh chia 15 chủ đề.
Mỗi từ có: word, meaning, example, pronunciation, topic, lesson_id
"""

SEED_VOCABULARIES = [
    # ─── Bài 1: Greetings & Introductions (30 từ) ───────────────────────────
    {"word": "hello", "meaning": "xin chào", "example": "Hello, how are you today?", "pronunciation": "həˈloʊ", "topic": "greetings", "lesson_id": 1},
    {"word": "goodbye", "meaning": "tạm biệt", "example": "Goodbye, see you tomorrow!", "pronunciation": "ɡʊdˈbaɪ", "topic": "greetings", "lesson_id": 1},
    {"word": "please", "meaning": "làm ơn / vui lòng", "example": "Please sit down.", "pronunciation": "pliːz", "topic": "greetings", "lesson_id": 1},
    {"word": "thank you", "meaning": "cảm ơn", "example": "Thank you for your help.", "pronunciation": "θæŋk juː", "topic": "greetings", "lesson_id": 1},
    {"word": "welcome", "meaning": "chào mừng", "example": "Welcome to our home!", "pronunciation": "ˈwɛlkəm", "topic": "greetings", "lesson_id": 1},
    {"word": "sorry", "meaning": "xin lỗi", "example": "I'm sorry I'm late.", "pronunciation": "ˈsɒri", "topic": "greetings", "lesson_id": 1},
    {"word": "excuse me", "meaning": "xin lỗi (làm phiền)", "example": "Excuse me, where is the station?", "pronunciation": "ɪkˈskjuːz miː", "topic": "greetings", "lesson_id": 1},
    {"word": "nice", "meaning": "tốt, đẹp, dễ chịu", "example": "It's a nice day today.", "pronunciation": "naɪs", "topic": "greetings", "lesson_id": 1},
    {"word": "meet", "meaning": "gặp", "example": "Nice to meet you!", "pronunciation": "miːt", "topic": "greetings", "lesson_id": 1},
    {"word": "name", "meaning": "tên", "example": "My name is John.", "pronunciation": "neɪm", "topic": "greetings", "lesson_id": 1},
    {"word": "friend", "meaning": "bạn bè", "example": "She is my best friend.", "pronunciation": "frɛnd", "topic": "greetings", "lesson_id": 1},
    {"word": "morning", "meaning": "buổi sáng", "example": "Good morning, class!", "pronunciation": "ˈmɔːrnɪŋ", "topic": "greetings", "lesson_id": 1},
    {"word": "afternoon", "meaning": "buổi chiều", "example": "Good afternoon, sir.", "pronunciation": "ˌæftərˈnuːn", "topic": "greetings", "lesson_id": 1},
    {"word": "evening", "meaning": "buổi tối", "example": "Good evening, everyone.", "pronunciation": "ˈiːvnɪŋ", "topic": "greetings", "lesson_id": 1},
    {"word": "night", "meaning": "đêm", "example": "Good night, sleep well.", "pronunciation": "naɪt", "topic": "greetings", "lesson_id": 1},
    {"word": "how", "meaning": "thế nào", "example": "How are you?", "pronunciation": "haʊ", "topic": "greetings", "lesson_id": 1},
    {"word": "fine", "meaning": "tốt, khỏe", "example": "I'm fine, thank you.", "pronunciation": "faɪn", "topic": "greetings", "lesson_id": 1},
    {"word": "introduce", "meaning": "giới thiệu", "example": "Let me introduce my friend.", "pronunciation": "ˌɪntrəˈduːs", "topic": "greetings", "lesson_id": 1},
    {"word": "call", "meaning": "gọi, gọi điện", "example": "Please call me Tom.", "pronunciation": "kɔːl", "topic": "greetings", "lesson_id": 1},
    {"word": "later", "meaning": "sau này, lát nữa", "example": "See you later!", "pronunciation": "ˈleɪtər", "topic": "greetings", "lesson_id": 1},
    {"word": "today", "meaning": "hôm nay", "example": "Today is Monday.", "pronunciation": "təˈdeɪ", "topic": "greetings", "lesson_id": 1},
    {"word": "tomorrow", "meaning": "ngày mai", "example": "See you tomorrow.", "pronunciation": "təˈmɒroʊ", "topic": "greetings", "lesson_id": 1},
    {"word": "yesterday", "meaning": "hôm qua", "example": "Yesterday was Sunday.", "pronunciation": "ˈjɛstərdeɪ", "topic": "greetings", "lesson_id": 1},
    {"word": "hello there", "meaning": "xin chào (thân mật)", "example": "Hello there! Long time no see.", "pronunciation": "həˈloʊ ðɛr", "topic": "greetings", "lesson_id": 1},
    {"word": "pleased", "meaning": "hân hạnh", "example": "Pleased to meet you.", "pronunciation": "pliːzd", "topic": "greetings", "lesson_id": 1},
    {"word": "greeting", "meaning": "lời chào", "example": "She sent her greetings to you.", "pronunciation": "ˈɡriːtɪŋ", "topic": "greetings", "lesson_id": 1},
    {"word": "polite", "meaning": "lịch sự", "example": "It's polite to say thank you.", "pronunciation": "pəˈlaɪt", "topic": "greetings", "lesson_id": 1},
    {"word": "colleague", "meaning": "đồng nghiệp", "example": "I work with my colleagues.", "pronunciation": "ˈkɑːliːɡ", "topic": "greetings", "lesson_id": 1},
    {"word": "neighbor", "meaning": "hàng xóm", "example": "My neighbor is very kind.", "pronunciation": "ˈneɪbər", "topic": "greetings", "lesson_id": 1},
    {"word": "farewell", "meaning": "lời từ biệt", "example": "They said their farewells.", "pronunciation": "ˌfɛrˈwɛl", "topic": "greetings", "lesson_id": 1},

    # ─── Bài 2: Family & Relationships (25 từ) ──────────────────────────────
    {"word": "mother", "meaning": "mẹ", "example": "My mother cooks dinner every day.", "pronunciation": "ˈmʌðər", "topic": "family", "lesson_id": 2},
    {"word": "father", "meaning": "bố", "example": "My father works in an office.", "pronunciation": "ˈfɑːðər", "topic": "family", "lesson_id": 2},
    {"word": "brother", "meaning": "anh/em trai", "example": "My brother is older than me.", "pronunciation": "ˈbrʌðər", "topic": "family", "lesson_id": 2},
    {"word": "sister", "meaning": "chị/em gái", "example": "My sister is a teacher.", "pronunciation": "ˈsɪstər", "topic": "family", "lesson_id": 2},
    {"word": "grandmother", "meaning": "bà", "example": "My grandmother tells stories.", "pronunciation": "ˈɡrænmʌðər", "topic": "family", "lesson_id": 2},
    {"word": "grandfather", "meaning": "ông", "example": "My grandfather likes gardening.", "pronunciation": "ˈɡrænfɑːðər", "topic": "family", "lesson_id": 2},
    {"word": "uncle", "meaning": "chú/bác", "example": "My uncle lives in Hanoi.", "pronunciation": "ˈʌŋkəl", "topic": "family", "lesson_id": 2},
    {"word": "aunt", "meaning": "cô/dì", "example": "My aunt is a doctor.", "pronunciation": "ænt", "topic": "family", "lesson_id": 2},
    {"word": "cousin", "meaning": "anh/chị em họ", "example": "My cousin studies abroad.", "pronunciation": "ˈkʌzən", "topic": "family", "lesson_id": 2},
    {"word": "husband", "meaning": "chồng", "example": "Her husband is a kind man.", "pronunciation": "ˈhʌzbənd", "topic": "family", "lesson_id": 2},
    {"word": "wife", "meaning": "vợ", "example": "His wife is a nurse.", "pronunciation": "waɪf", "topic": "family", "lesson_id": 2},
    {"word": "son", "meaning": "con trai", "example": "They have two sons.", "pronunciation": "sʌn", "topic": "family", "lesson_id": 2},
    {"word": "daughter", "meaning": "con gái", "example": "My daughter loves cats.", "pronunciation": "ˈdɔːtər", "topic": "family", "lesson_id": 2},
    {"word": "parent", "meaning": "phụ huynh", "example": "Parents love their children.", "pronunciation": "ˈpɛrənt", "topic": "family", "lesson_id": 2},
    {"word": "child", "meaning": "đứa trẻ", "example": "The child is playing outside.", "pronunciation": "tʃaɪld", "topic": "family", "lesson_id": 2},
    {"word": "baby", "meaning": "em bé", "example": "The baby is sleeping.", "pronunciation": "ˈbeɪbi", "topic": "family", "lesson_id": 2},
    {"word": "family", "meaning": "gia đình", "example": "We are a happy family.", "pronunciation": "ˈfæməli", "topic": "family", "lesson_id": 2},
    {"word": "relative", "meaning": "họ hàng", "example": "We visit our relatives at Tet.", "pronunciation": "ˈrɛlətɪv", "topic": "family", "lesson_id": 2},
    {"word": "marriage", "meaning": "hôn nhân", "example": "They have a happy marriage.", "pronunciation": "ˈmærɪdʒ", "topic": "family", "lesson_id": 2},
    {"word": "wedding", "meaning": "đám cưới", "example": "The wedding was beautiful.", "pronunciation": "ˈwɛdɪŋ", "topic": "family", "lesson_id": 2},
    {"word": "divorce", "meaning": "ly hôn", "example": "Divorce can be difficult.", "pronunciation": "dɪˈvɔːrs", "topic": "family", "lesson_id": 2},
    {"word": "generation", "meaning": "thế hệ", "example": "The younger generation loves technology.", "pronunciation": "ˌdʒɛnəˈreɪʃən", "topic": "family", "lesson_id": 2},
    {"word": "ancestor", "meaning": "tổ tiên", "example": "We honor our ancestors.", "pronunciation": "ˈænsɛstər", "topic": "family", "lesson_id": 2},
    {"word": "twin", "meaning": "sinh đôi", "example": "They are twin sisters.", "pronunciation": "twɪn", "topic": "family", "lesson_id": 2},
    {"word": "adopt", "meaning": "nhận nuôi", "example": "They adopted a child.", "pronunciation": "əˈdɒpt", "topic": "family", "lesson_id": 2},

    # ─── Bài 3: Numbers, Time & Dates (30 từ) ──────────────────────────────
    {"word": "one", "meaning": "một", "example": "I have one book.", "pronunciation": "wʌn", "topic": "numbers", "lesson_id": 3},
    {"word": "first", "meaning": "thứ nhất", "example": "She came first in the race.", "pronunciation": "fɜːrst", "topic": "numbers", "lesson_id": 3},
    {"word": "second", "meaning": "thứ hai", "example": "February is the second month.", "pronunciation": "ˈsɛkənd", "topic": "numbers", "lesson_id": 3},
    {"word": "third", "meaning": "thứ ba", "example": "He finished third.", "pronunciation": "θɜːrd", "topic": "numbers", "lesson_id": 3},
    {"word": "half", "meaning": "một nửa", "example": "Half of the cake is gone.", "pronunciation": "hæf", "topic": "numbers", "lesson_id": 3},
    {"word": "double", "meaning": "gấp đôi", "example": "Double the recipe, please.", "pronunciation": "ˈdʌbəl", "topic": "numbers", "lesson_id": 3},
    {"word": "zero", "meaning": "số không", "example": "The temperature is zero.", "pronunciation": "ˈzɪroʊ", "topic": "numbers", "lesson_id": 3},
    {"word": "hundred", "meaning": "trăm", "example": "There are one hundred students.", "pronunciation": "ˈhʌndrəd", "topic": "numbers", "lesson_id": 3},
    {"word": "thousand", "meaning": "nghìn", "example": "This costs two thousand dong.", "pronunciation": "ˈθaʊzənd", "topic": "numbers", "lesson_id": 3},
    {"word": "million", "meaning": "triệu", "example": "The city has one million people.", "pronunciation": "ˈmɪljən", "topic": "numbers", "lesson_id": 3},
    {"word": "time", "meaning": "thời gian", "example": "What time is it?", "pronunciation": "taɪm", "topic": "numbers", "lesson_id": 3},
    {"word": "hour", "meaning": "giờ", "example": "I study for one hour daily.", "pronunciation": "aʊər", "topic": "numbers", "lesson_id": 3},
    {"word": "minute", "meaning": "phút", "example": "Wait a minute, please.", "pronunciation": "ˈmɪnɪt", "topic": "numbers", "lesson_id": 3},
    {"word": "o'clock", "meaning": "giờ đúng", "example": "It's three o'clock.", "pronunciation": "əˈklɒk", "topic": "numbers", "lesson_id": 3},
    {"word": "early", "meaning": "sớm", "example": "I wake up early every day.", "pronunciation": "ˈɜːrli", "topic": "numbers", "lesson_id": 3},
    {"word": "late", "meaning": "muộn", "example": "Don't be late for class.", "pronunciation": "leɪt", "topic": "numbers", "lesson_id": 3},
    {"word": "date", "meaning": "ngày tháng", "example": "What's the date today?", "pronunciation": "deɪt", "topic": "numbers", "lesson_id": 3},
    {"word": "month", "meaning": "tháng", "example": "January is the first month.", "pronunciation": "mʌnθ", "topic": "numbers", "lesson_id": 3},
    {"word": "year", "meaning": "năm", "example": "This year is 2025.", "pronunciation": "jɪr", "topic": "numbers", "lesson_id": 3},
    {"word": "week", "meaning": "tuần", "example": "There are seven days in a week.", "pronunciation": "wiːk", "topic": "numbers", "lesson_id": 3},
    {"word": "Monday", "meaning": "thứ Hai", "example": "Monday is the first workday.", "pronunciation": "ˈmʌndeɪ", "topic": "numbers", "lesson_id": 3},
    {"word": "Tuesday", "meaning": "thứ Ba", "example": "Tuesday is my favorite day.", "pronunciation": "ˈtjuːzdeɪ", "topic": "numbers", "lesson_id": 3},
    {"word": "Wednesday", "meaning": "thứ Tư", "example": "Wednesday is the middle of the week.", "pronunciation": "ˈwɛnzdeɪ", "topic": "numbers", "lesson_id": 3},
    {"word": "Thursday", "meaning": "thứ Năm", "example": "Thursday comes after Wednesday.", "pronunciation": "ˈθɜːrzdeɪ", "topic": "numbers", "lesson_id": 3},
    {"word": "Friday", "meaning": "thứ Sáu", "example": "Friday is almost the weekend!", "pronunciation": "ˈfraɪdeɪ", "topic": "numbers", "lesson_id": 3},
    {"word": "Saturday", "meaning": "thứ Bảy", "example": "Saturday is a holiday.", "pronunciation": "ˈsætərdeɪ", "topic": "numbers", "lesson_id": 3},
    {"word": "Sunday", "meaning": "Chủ nhật", "example": "Sunday is a day of rest.", "pronunciation": "ˈsʌndeɪ", "topic": "numbers", "lesson_id": 3},
    {"word": "January", "meaning": "tháng Một", "example": "New Year is in January.", "pronunciation": "ˈdʒænjueri", "topic": "numbers", "lesson_id": 3},
    {"word": "schedule", "meaning": "lịch trình", "example": "Check the bus schedule.", "pronunciation": "ˈʃɛdjuːl", "topic": "numbers", "lesson_id": 3},
    {"word": "deadline", "meaning": "hạn chót", "example": "The deadline is Friday.", "pronunciation": "ˈdɛdlaɪn", "topic": "numbers", "lesson_id": 3},

    # ─── Bài 4: Daily Routines (30 từ) ──────────────────────────────────
    {"word": "wake up", "meaning": "thức dậy", "example": "I wake up at 6 AM.", "pronunciation": "weɪk ʌp", "topic": "daily", "lesson_id": 4},
    {"word": "get up", "meaning": "ngồi dậy", "example": "I get up immediately.", "pronunciation": "ɡɛt ʌp", "topic": "daily", "lesson_id": 4},
    {"word": "brush", "meaning": "chải, đánh", "example": "I brush my teeth twice a day.", "pronunciation": "brʌʃ", "topic": "daily", "lesson_id": 4},
    {"word": "shower", "meaning": "tắm vòi sen", "example": "I take a shower every morning.", "pronunciation": "ˈʃaʊər", "topic": "daily", "lesson_id": 4},
    {"word": "dress", "meaning": "mặc quần áo", "example": "I dress quickly in the morning.", "pronunciation": "drɛs", "topic": "daily", "lesson_id": 4},
    {"word": "breakfast", "meaning": "bữa sáng", "example": "I eat breakfast at 7 AM.", "pronunciation": "ˈbrɛkfəst", "topic": "daily", "lesson_id": 4},
    {"word": "lunch", "meaning": "bữa trưa", "example": "We have lunch at noon.", "pronunciation": "lʌntʃ", "topic": "daily", "lesson_id": 4},
    {"word": "dinner", "meaning": "bữa tối", "example": "Dinner is ready!", "pronunciation": "ˈdɪnər", "topic": "daily", "lesson_id": 4},
    {"word": "go to school", "meaning": "đi học", "example": "I go to school by bus.", "pronunciation": "ɡoʊ tuː skuːl", "topic": "daily", "lesson_id": 4},
    {"word": "go to work", "meaning": "đi làm", "example": "My father goes to work at 8 AM.", "pronunciation": "ɡoʊ tuː wɜːrk", "topic": "daily", "lesson_id": 4},
    {"word": "return home", "meaning": "về nhà", "example": "I return home at 5 PM.", "pronunciation": "rɪˈtɜːrn hoʊm", "topic": "daily", "lesson_id": 4},
    {"word": "cook", "meaning": "nấu ăn", "example": "I cook dinner for my family.", "pronunciation": "kʊk", "topic": "daily", "lesson_id": 4},
    {"word": "clean", "meaning": "dọn dẹp", "example": "I clean my room every weekend.", "pronunciation": "kliːn", "topic": "daily", "lesson_id": 4},
    {"word": "wash", "meaning": "rửa, giặt", "example": "Please wash your hands.", "pronunciation": "wɒʃ", "topic": "daily", "lesson_id": 4},
    {"word": "study", "meaning": "học", "example": "I study English every evening.", "pronunciation": "ˈstʌdi", "topic": "daily", "lesson_id": 4},
    {"word": "read", "meaning": "đọc", "example": "I like to read books.", "pronunciation": "riːd", "topic": "daily", "lesson_id": 4},
    {"word": "write", "meaning": "viết", "example": "Please write your name here.", "pronunciation": "raɪt", "topic": "daily", "lesson_id": 4},
    {"word": "homework", "meaning": "bài tập về nhà", "example": "I do homework after dinner.", "pronunciation": "ˈhoʊmwɜːrk", "topic": "daily", "lesson_id": 4},
    {"word": "sleep", "meaning": "ngủ", "example": "I sleep for eight hours.", "pronunciation": "sliːp", "topic": "daily", "lesson_id": 4},
    {"word": "alarm", "meaning": "báo thức", "example": "My alarm rings at 6 AM.", "pronunciation": "əˈlɑːrm", "topic": "daily", "lesson_id": 4},
    {"word": "prepare", "meaning": "chuẩn bị", "example": "I prepare my bag for school.", "pronunciation": "prɪˈpɛr", "topic": "daily", "lesson_id": 4},
    {"word": "exercise", "meaning": "tập thể dục", "example": "I exercise for 30 minutes daily.", "pronunciation": "ˈɛksərsaɪz", "topic": "daily", "lesson_id": 4},
    {"word": "routine", "meaning": "thói quen hàng ngày", "example": "My morning routine is simple.", "pronunciation": "ruːˈtiːn", "topic": "daily", "lesson_id": 4},
    {"word": "often", "meaning": "thường xuyên", "example": "I often read before bed.", "pronunciation": "ˈɔːfən", "topic": "daily", "lesson_id": 4},
    {"word": "always", "meaning": "luôn luôn", "example": "I always brush my teeth.", "pronunciation": "ˈɔːlweɪz", "topic": "daily", "lesson_id": 4},
    {"word": "usually", "meaning": "thường thường", "example": "I usually wake up at 6.", "pronunciation": "ˈjuːʒuəli", "topic": "daily", "lesson_id": 4},
    {"word": "sometimes", "meaning": "thỉnh thoảng", "example": "I sometimes watch TV.", "pronunciation": "ˈsʌmtaɪmz", "topic": "daily", "lesson_id": 4},
    {"word": "rarely", "meaning": "hiếm khi", "example": "I rarely eat fast food.", "pronunciation": "ˈrɛrli", "topic": "daily", "lesson_id": 4},
    {"word": "commute", "meaning": "đi lại (hàng ngày)", "example": "My commute takes 30 minutes.", "pronunciation": "kəˈmjuːt", "topic": "daily", "lesson_id": 4},
    {"word": "relax", "meaning": "thư giãn", "example": "I relax by listening to music.", "pronunciation": "rɪˈlæks", "topic": "daily", "lesson_id": 4},

    # ─── Bài 5: Food & Drinks (35 từ) ────────────────────────────────────
    {"word": "rice", "meaning": "cơm, gạo", "example": "I eat rice every day.", "pronunciation": "raɪs", "topic": "food", "lesson_id": 5},
    {"word": "chicken", "meaning": "thịt gà", "example": "Chicken is my favorite meat.", "pronunciation": "ˈtʃɪkɪn", "topic": "food", "lesson_id": 5},
    {"word": "beef", "meaning": "thịt bò", "example": "I like beef noodles.", "pronunciation": "biːf", "topic": "food", "lesson_id": 5},
    {"word": "pork", "meaning": "thịt lợn", "example": "This dish has pork.", "pronunciation": "pɔːrk", "topic": "food", "lesson_id": 5},
    {"word": "fish", "meaning": "cá", "example": "Fish is healthy.", "pronunciation": "fɪʃ", "topic": "food", "lesson_id": 5},
    {"word": "vegetable", "meaning": "rau củ", "example": "Eat more vegetables!", "pronunciation": "ˈvɛdʒtəbəl", "topic": "food", "lesson_id": 5},
    {"word": "fruit", "meaning": "trái cây", "example": "I eat fruit for dessert.", "pronunciation": "fruːt", "topic": "food", "lesson_id": 5},
    {"word": "apple", "meaning": "quả táo", "example": "An apple a day keeps the doctor away.", "pronunciation": "ˈæpəl", "topic": "food", "lesson_id": 5},
    {"word": "banana", "meaning": "quả chuối", "example": "Bananas are yellow.", "pronunciation": "bəˈnænə", "topic": "food", "lesson_id": 5},
    {"word": "bread", "meaning": "bánh mì", "example": "I eat bread for breakfast.", "pronunciation": "brɛd", "topic": "food", "lesson_id": 5},
    {"word": "milk", "meaning": "sữa", "example": "I drink milk every morning.", "pronunciation": "mɪlk", "topic": "food", "lesson_id": 5},
    {"word": "egg", "meaning": "trứng", "example": "I have two eggs for breakfast.", "pronunciation": "ɛɡ", "topic": "food", "lesson_id": 5},
    {"word": "cheese", "meaning": "phô mai", "example": "Cheese is made from milk.", "pronunciation": "tʃiːz", "topic": "food", "lesson_id": 5},
    {"word": "coffee", "meaning": "cà phê", "example": "I drink coffee every morning.", "pronunciation": "ˈkɒfi", "topic": "food", "lesson_id": 5},
    {"word": "tea", "meaning": "trà", "example": "Would you like some tea?", "pronunciation": "tiː", "topic": "food", "lesson_id": 5},
    {"word": "water", "meaning": "nước", "example": "Drink more water every day.", "pronunciation": "ˈwɔːtər", "topic": "food", "lesson_id": 5},
    {"word": "juice", "meaning": "nước ép", "example": "Orange juice is fresh.", "pronunciation": "dʒuːs", "topic": "food", "lesson_id": 5},
    {"word": "soup", "meaning": "súp, canh", "example": "The soup is delicious.", "pronunciation": "suːp", "topic": "food", "lesson_id": 5},
    {"word": "noodle", "meaning": "mì, phở", "example": "I love Vietnamese noodles.", "pronunciation": "ˈnuːdəl", "topic": "food", "lesson_id": 5},
    {"word": "cake", "meaning": "bánh ngọt", "example": "She baked a birthday cake.", "pronunciation": "keɪk", "topic": "food", "lesson_id": 5},
    {"word": "candy", "meaning": "kẹo", "example": "Children love candy.", "pronunciation": "ˈkændi", "topic": "food", "lesson_id": 5},
    {"word": "salt", "meaning": "muối", "example": "Add a little salt.", "pronunciation": "sɔːlt", "topic": "food", "lesson_id": 5},
    {"word": "sugar", "meaning": "đường", "example": "Too much sugar is bad.", "pronunciation": "ˈʃʊɡər", "topic": "food", "lesson_id": 5},
    {"word": "spicy", "meaning": "cay", "example": "Vietnamese food is often spicy.", "pronunciation": "ˈspaɪsi", "topic": "food", "lesson_id": 5},
    {"word": "sweet", "meaning": "ngọt", "example": "This cake is very sweet.", "pronunciation": "swiːt", "topic": "food", "lesson_id": 5},
    {"word": "sour", "meaning": "chua", "example": "Lemons taste sour.", "pronunciation": "saʊər", "topic": "food", "lesson_id": 5},
    {"word": "bitter", "meaning": "đắng", "example": "Black coffee is bitter.", "pronunciation": "ˈbɪtər", "topic": "food", "lesson_id": 5},
    {"word": "delicious", "meaning": "ngon", "example": "The food is delicious!", "pronunciation": "dɪˈlɪʃəs", "topic": "food", "lesson_id": 5},
    {"word": "hungry", "meaning": "đói", "example": "I'm hungry. Let's eat!", "pronunciation": "ˈhʌŋɡri", "topic": "food", "lesson_id": 5},
    {"word": "thirsty", "meaning": "khát", "example": "I'm thirsty. I need water.", "pronunciation": "ˈθɜːrsti", "topic": "food", "lesson_id": 5},
    {"word": "restaurant", "meaning": "nhà hàng", "example": "Let's go to a restaurant.", "pronunciation": "ˈrɛstərɒnt", "topic": "food", "lesson_id": 5},
    {"word": "menu", "meaning": "thực đơn", "example": "Can I see the menu?", "pronunciation": "ˈmɛnjuː", "topic": "food", "lesson_id": 5},
    {"word": "order", "meaning": "gọi món", "example": "I'd like to order now.", "pronunciation": "ˈɔːrdər", "topic": "food", "lesson_id": 5},
    {"word": "bill", "meaning": "hóa đơn", "example": "Can I have the bill?", "pronunciation": "bɪl", "topic": "food", "lesson_id": 5},
    {"word": "tip", "meaning": "tiền boa", "example": "We left a 10% tip.", "pronunciation": "tɪp", "topic": "food", "lesson_id": 5},

    # ─── Bài 6: Travel & Directions (30 từ) ──────────────────────────────
    {"word": "airport", "meaning": "sân bay", "example": "We arrived at the airport.", "pronunciation": "ˈɛrpɔːrt", "topic": "travel", "lesson_id": 6},
    {"word": "hotel", "meaning": "khách sạn", "example": "We stayed at a nice hotel.", "pronunciation": "hoʊˈtɛl", "topic": "travel", "lesson_id": 6},
    {"word": "ticket", "meaning": "vé", "example": "I bought a plane ticket.", "pronunciation": "ˈtɪkɪt", "topic": "travel", "lesson_id": 6},
    {"word": "passport", "meaning": "hộ chiếu", "example": "Don't forget your passport!", "pronunciation": "ˈpæspɔːrt", "topic": "travel", "lesson_id": 6},
    {"word": "luggage", "meaning": "hành lý", "example": "My luggage is heavy.", "pronunciation": "ˈlʌɡɪdʒ", "topic": "travel", "lesson_id": 6},
    {"word": "map", "meaning": "bản đồ", "example": "Let's look at the map.", "pronunciation": "mæp", "topic": "travel", "lesson_id": 6},
    {"word": "direction", "meaning": "hướng, chỉ đường", "example": "Can you give me directions?", "pronunciation": "dɪˈrɛkʃən", "topic": "travel", "lesson_id": 6},
    {"word": "straight", "meaning": "thẳng", "example": "Go straight ahead.", "pronunciation": "streɪt", "topic": "travel", "lesson_id": 6},
    {"word": "left", "meaning": "trái", "example": "Turn left at the corner.", "pronunciation": "lɛft", "topic": "travel", "lesson_id": 6},
    {"word": "right", "meaning": "phải", "example": "Turn right at the traffic light.", "pronunciation": "raɪt", "topic": "travel", "lesson_id": 6},
    {"word": "station", "meaning": "nhà ga", "example": "The train station is near.", "pronunciation": "ˈsteɪʃən", "topic": "travel", "lesson_id": 6},
    {"word": "bus", "meaning": "xe buýt", "example": "Take bus number 10.", "pronunciation": "bʌs", "topic": "travel", "lesson_id": 6},
    {"word": "train", "meaning": "tàu hỏa", "example": "The train leaves at 8 AM.", "pronunciation": "treɪn", "topic": "travel", "lesson_id": 6},
    {"word": "taxi", "meaning": "xe taxi", "example": "Let's take a taxi.", "pronunciation": "ˈtæksi", "topic": "travel", "lesson_id": 6},
    {"word": "flight", "meaning": "chuyến bay", "example": "The flight takes 2 hours.", "pronunciation": "flaɪt", "topic": "travel", "lesson_id": 6},
    {"word": "trip", "meaning": "chuyến đi", "example": "We had a wonderful trip.", "pronunciation": "trɪp", "topic": "travel", "lesson_id": 6},
    {"word": "tourist", "meaning": "khách du lịch", "example": "The city is full of tourists.", "pronunciation": "ˈtʊrɪst", "topic": "travel", "lesson_id": 6},
    {"word": "suitcase", "meaning": "va li", "example": "I packed my suitcase.", "pronunciation": "ˈsuːtkeɪs", "topic": "travel", "lesson_id": 6},
    {"word": "departure", "meaning": "khởi hành", "example": "Departure time is 9 AM.", "pronunciation": "dɪˈpɑːrtʃər", "topic": "travel", "lesson_id": 6},
    {"word": "arrival", "meaning": "đến nơi", "example": "Arrival at 10 PM.", "pronunciation": "əˈraɪvəl", "topic": "travel", "lesson_id": 6},
    {"word": "delay", "meaning": "hoãn, trễ", "example": "The flight is delayed.", "pronunciation": "dɪˈleɪ", "topic": "travel", "lesson_id": 6},
    {"word": "beach", "meaning": "bãi biển", "example": "Let's go to the beach!", "pronunciation": "biːtʃ", "topic": "travel", "lesson_id": 6},
    {"word": "mountain", "meaning": "núi", "example": "The mountain is beautiful.", "pronunciation": "ˈmaʊntɪn", "topic": "travel", "lesson_id": 6},
    {"word": "museum", "meaning": "bảo tàng", "example": "We visited the museum.", "pronunciation": "mjuːˈziːəm", "topic": "travel", "lesson_id": 6},
    {"word": "souvenir", "meaning": "quà lưu niệm", "example": "I bought some souvenirs.", "pronunciation": "ˌsuːvəˈnɪr", "topic": "travel", "lesson_id": 6},
    {"word": "reservation", "meaning": "đặt trước", "example": "I have a hotel reservation.", "pronunciation": "ˌrɛzərˈveɪʃən", "topic": "travel", "lesson_id": 6},
    {"word": "currency", "meaning": "tiền tệ", "example": "I need to exchange currency.", "pronunciation": "ˈkɜːrənsi", "topic": "travel", "lesson_id": 6},
    {"word": "guide", "meaning": "hướng dẫn viên", "example": "The tour guide is friendly.", "pronunciation": "ɡaɪd", "topic": "travel", "lesson_id": 6},
    {"word": "sightseeing", "meaning": "tham quan", "example": "We went sightseeing in Paris.", "pronunciation": "ˈsaɪtsiːɪŋ", "topic": "travel", "lesson_id": 6},
    {"word": "adventure", "meaning": "cuộc phiêu lưu", "example": "Travel is an adventure!", "pronunciation": "ədˈvɛntʃər", "topic": "travel", "lesson_id": 6},

    # ─── Bài 7: Shopping & Prices (30 từ) ─────────────────────────────────
    {"word": "price", "meaning": "giá cả", "example": "What is the price?", "pronunciation": "praɪs", "topic": "shopping", "lesson_id": 7},
    {"word": "cost", "meaning": "chi phí", "example": "How much does it cost?", "pronunciation": "kɒst", "topic": "shopping", "lesson_id": 7},
    {"word": "cheap", "meaning": "rẻ", "example": "This shirt is cheap.", "pronunciation": "tʃiːp", "topic": "shopping", "lesson_id": 7},
    {"word": "expensive", "meaning": "đắt", "example": "That bag is expensive.", "pronunciation": "ɪkˈspɛnsɪv", "topic": "shopping", "lesson_id": 7},
    {"word": "discount", "meaning": "giảm giá", "example": "There is a 20% discount.", "pronunciation": "ˈdɪskaʊnt", "topic": "shopping", "lesson_id": 7},
    {"word": "sale", "meaning": "bán hàng, giảm giá", "example": "The store has a big sale.", "pronunciation": "seɪl", "topic": "shopping", "lesson_id": 7},
    {"word": "receipt", "meaning": "hóa đơn", "example": "Keep your receipt.", "pronunciation": "rɪˈsiːt", "topic": "shopping", "lesson_id": 7},
    {"word": "cash", "meaning": "tiền mặt", "example": "Do you pay with cash?", "pronunciation": "kæʃ", "topic": "shopping", "lesson_id": 7},
    {"word": "credit card", "meaning": "thẻ tín dụng", "example": "I'll pay by credit card.", "pronunciation": "ˈkrɛdɪt kɑːrd", "topic": "shopping", "lesson_id": 7},
    {"word": "wallet", "meaning": "ví", "example": "I lost my wallet.", "pronunciation": "ˈwɒlɪt", "topic": "shopping", "lesson_id": 7},
    {"word": "size", "meaning": "kích cỡ", "example": "What size do you wear?", "pronunciation": "saɪz", "topic": "shopping", "lesson_id": 7},
    {"word": "color", "meaning": "màu sắc", "example": "My favorite color is blue.", "pronunciation": "ˈkʌlər", "topic": "shopping", "lesson_id": 7},
    {"word": "try on", "meaning": "mặc thử", "example": "Can I try this on?", "pronunciation": "traɪ ɒn", "topic": "shopping", "lesson_id": 7},
    {"word": "fit", "meaning": "vừa vặn", "example": "This dress fits perfectly.", "pronunciation": "fɪt", "topic": "shopping", "lesson_id": 7},
    {"word": "change", "meaning": "tiền lẻ, thay đổi", "example": "Here is your change.", "pronunciation": "tʃeɪndʒ", "topic": "shopping", "lesson_id": 7},
    {"word": "return", "meaning": "trả lại", "example": "I'd like to return this item.", "pronunciation": "rɪˈtɜːrn", "topic": "shopping", "lesson_id": 7},
    {"word": "exchange", "meaning": "đổi hàng", "example": "Can I exchange this for a larger size?", "pronunciation": "ɪksˈtʃeɪndʒ", "topic": "shopping", "lesson_id": 7},
    {"word": "shop", "meaning": "cửa hàng", "example": "The shop opens at 9 AM.", "pronunciation": "ʃɒp", "topic": "shopping", "lesson_id": 7},
    {"word": "store", "meaning": "cửa hàng (lớn)", "example": "Let's go to the department store.", "pronunciation": "stɔːr", "topic": "shopping", "lesson_id": 7},
    {"word": "supermarket", "meaning": "siêu thị", "example": "I buy food at the supermarket.", "pronunciation": "ˈsuːpərˌmɑːrkɪt", "topic": "shopping", "lesson_id": 7},
    {"word": "bargain", "meaning": "mặc cả, giá hời", "example": "This was a real bargain!", "pronunciation": "ˈbɑːrɡɪn", "topic": "shopping", "lesson_id": 7},
    {"word": "brand", "meaning": "nhãn hiệu", "example": "I like this brand.", "pronunciation": "brænd", "topic": "shopping", "lesson_id": 7},
    {"word": "quality", "meaning": "chất lượng", "example": "The quality is excellent.", "pronunciation": "ˈkwɒləti", "topic": "shopping", "lesson_id": 7},
    {"word": "guarantee", "meaning": "bảo hành", "example": "The product has a 2-year guarantee.", "pronunciation": "ˌɡærənˈtiː", "topic": "shopping", "lesson_id": 7},
    {"word": "customer", "meaning": "khách hàng", "example": "The customer is always right.", "pronunciation": "ˈkʌstəmər", "topic": "shopping", "lesson_id": 7},
    {"word": "cashier", "meaning": "thu ngân", "example": "Pay at the cashier.", "pronunciation": "kæˈʃɪr", "topic": "shopping", "lesson_id": 7},
    {"word": "counter", "meaning": "quầy", "example": "Go to counter number 3.", "pronunciation": "ˈkaʊntər", "topic": "shopping", "lesson_id": 7},
    {"word": "receipt", "meaning": "biên lai", "example": "Here is your receipt.", "pronunciation": "rɪˈsiːt", "topic": "shopping", "lesson_id": 7},
    {"word": "refund", "meaning": "hoàn tiền", "example": "I want a full refund.", "pronunciation": "ˈriːfʌnd", "topic": "shopping", "lesson_id": 7},
    {"word": "offer", "meaning": "ưu đãi", "example": "This is a special offer.", "pronunciation": "ˈɒfər", "topic": "shopping", "lesson_id": 7},

    # ─── Bài 8: Weather & Seasons (25 từ) ────────────────────────────────
    {"word": "sunny", "meaning": "nắng", "example": "It's a sunny day.", "pronunciation": "ˈsʌni", "topic": "weather", "lesson_id": 8},
    {"word": "rainy", "meaning": "mưa", "example": "It's rainy today.", "pronunciation": "ˈreɪni", "topic": "weather", "lesson_id": 8},
    {"word": "cloudy", "meaning": "nhiều mây", "example": "The sky is cloudy.", "pronunciation": "ˈklaʊdi", "topic": "weather", "lesson_id": 8},
    {"word": "windy", "meaning": "nhiều gió", "example": "It's very windy outside.", "pronunciation": "ˈwɪndi", "topic": "weather", "lesson_id": 8},
    {"word": "cold", "meaning": "lạnh", "example": "Winter is cold.", "pronunciation": "koʊld", "topic": "weather", "lesson_id": 8},
    {"word": "hot", "meaning": "nóng", "example": "Summer is very hot.", "pronunciation": "hɒt", "topic": "weather", "lesson_id": 8},
    {"word": "warm", "meaning": "ấm áp", "example": "Spring weather is warm.", "pronunciation": "wɔːrm", "topic": "weather", "lesson_id": 8},
    {"word": "cool", "meaning": "mát mẻ", "example": "Autumn is cool.", "pronunciation": "kuːl", "topic": "weather", "lesson_id": 8},
    {"word": "temperature", "meaning": "nhiệt độ", "example": "The temperature is 30 degrees.", "pronunciation": "ˈtɛmprətʃər", "topic": "weather", "lesson_id": 8},
    {"word": "spring", "meaning": "mùa xuân", "example": "Flowers bloom in spring.", "pronunciation": "sprɪŋ", "topic": "weather", "lesson_id": 8},
    {"word": "summer", "meaning": "mùa hè", "example": "I love summer vacation.", "pronunciation": "ˈsʌmər", "topic": "weather", "lesson_id": 8},
    {"word": "autumn", "meaning": "mùa thu", "example": "Leaves fall in autumn.", "pronunciation": "ˈɔːtəm", "topic": "weather", "lesson_id": 8},
    {"word": "winter", "meaning": "mùa đông", "example": "It snows in winter.", "pronunciation": "ˈwɪntər", "topic": "weather", "lesson_id": 8},
    {"word": "rain", "meaning": "cơn mưa", "example": "The rain is heavy.", "pronunciation": "reɪn", "topic": "weather", "lesson_id": 8},
    {"word": "snow", "meaning": "tuyết", "example": "It snows in December.", "pronunciation": "snoʊ", "topic": "weather", "lesson_id": 8},
    {"word": "storm", "meaning": "bão", "example": "The storm is coming.", "pronunciation": "stɔːrm", "topic": "weather", "lesson_id": 8},
    {"word": "forecast", "meaning": "dự báo", "example": "Check the weather forecast.", "pronunciation": "ˈfɔːrkæst", "topic": "weather", "lesson_id": 8},
    {"word": "humid", "meaning": "ẩm ướt", "example": "Summer is humid in Vietnam.", "pronunciation": "ˈhjuːmɪd", "topic": "weather", "lesson_id": 8},
    {"word": "dry", "meaning": "khô ráo", "example": "The weather is dry today.", "pronunciation": "draɪ", "topic": "weather", "lesson_id": 8},
    {"word": "fog", "meaning": "sương mù", "example": "The fog is thick.", "pronunciation": "fɒɡ", "topic": "weather", "lesson_id": 8},
    {"word": "lightning", "meaning": "chớp", "example": "Lightning lit up the sky.", "pronunciation": "ˈlaɪtnɪŋ", "topic": "weather", "lesson_id": 8},
    {"word": "thunder", "meaning": "sấm", "example": "Thunder followed the lightning.", "pronunciation": "ˈθʌndər", "topic": "weather", "lesson_id": 8},
    {"word": "flood", "meaning": "lũ lụt", "example": "The flood caused damage.", "pronunciation": "flʌd", "topic": "weather", "lesson_id": 8},
    {"word": "drought", "meaning": "hạn hán", "example": "The drought lasted three months.", "pronunciation": "draʊt", "topic": "weather", "lesson_id": 8},
    {"word": "climate", "meaning": "khí hậu", "example": "Climate change is a global issue.", "pronunciation": "ˈklaɪmət", "topic": "weather", "lesson_id": 8},

    # ─── Bài 9: Health & Body (30 từ) ────────────────────────────────────
    {"word": "head", "meaning": "cái đầu", "example": "I have a headache.", "pronunciation": "hɛd", "topic": "health", "lesson_id": 9},
    {"word": "face", "meaning": "khuôn mặt", "example": "She has a pretty face.", "pronunciation": "feɪs", "topic": "health", "lesson_id": 9},
    {"word": "eye", "meaning": "mắt", "example": "She has blue eyes.", "pronunciation": "aɪ", "topic": "health", "lesson_id": 9},
    {"word": "ear", "meaning": "tai", "example": "I can hear with my ears.", "pronunciation": "ɪr", "topic": "health", "lesson_id": 9},
    {"word": "nose", "meaning": "mũi", "example": "He has a big nose.", "pronunciation": "noʊz", "topic": "health", "lesson_id": 9},
    {"word": "mouth", "meaning": "miệng", "example": "Open your mouth.", "pronunciation": "maʊθ", "topic": "health", "lesson_id": 9},
    {"word": "hand", "meaning": "bàn tay", "example": "Wash your hands.", "pronunciation": "hænd", "topic": "health", "lesson_id": 9},
    {"word": "arm", "meaning": "cánh tay", "example": "She broke her arm.", "pronunciation": "ɑːrm", "topic": "health", "lesson_id": 9},
    {"word": "leg", "meaning": "chân (từ đùi xuống)", "example": "He hurt his leg.", "pronunciation": "lɛɡ", "topic": "health", "lesson_id": 9},
    {"word": "foot", "meaning": "bàn chân", "example": "My foot hurts.", "pronunciation": "fʊt", "topic": "health", "lesson_id": 9},
    {"word": "stomach", "meaning": "dạ dày, bụng", "example": "I have a stomachache.", "pronunciation": "ˈstʌmək", "topic": "health", "lesson_id": 9},
    {"word": "heart", "meaning": "tim", "example": "Exercise is good for your heart.", "pronunciation": "hɑːrt", "topic": "health", "lesson_id": 9},
    {"word": "doctor", "meaning": "bác sĩ", "example": "You should see a doctor.", "pronunciation": "ˈdɒktər", "topic": "health", "lesson_id": 9},
    {"word": "nurse", "meaning": "y tá", "example": "The nurse is kind.", "pronunciation": "nɜːrs", "topic": "health", "lesson_id": 9},
    {"word": "hospital", "meaning": "bệnh viện", "example": "He went to the hospital.", "pronunciation": "ˈhɒspɪtəl", "topic": "health", "lesson_id": 9},
    {"word": "medicine", "meaning": "thuốc", "example": "Take this medicine.", "pronunciation": "ˈmɛdɪsɪn", "topic": "health", "lesson_id": 9},
    {"word": "pain", "meaning": "cơn đau", "example": "I have a pain in my back.", "pronunciation": "peɪn", "topic": "health", "lesson_id": 9},
    {"word": "fever", "meaning": "sốt", "example": "She has a high fever.", "pronunciation": "ˈfiːvər", "topic": "health", "lesson_id": 9},
    {"word": "cold", "meaning": "cảm lạnh", "example": "I caught a cold.", "pronunciation": "koʊld", "topic": "health", "lesson_id": 9},
    {"word": "cough", "meaning": "ho", "example": "He has a bad cough.", "pronunciation": "kɒf", "topic": "health", "lesson_id": 9},
    {"word": "fitness", "meaning": "thể lực", "example": "Regular exercise improves fitness.", "pronunciation": "ˈfɪtnəs", "topic": "health", "lesson_id": 9},
    {"word": "diet", "meaning": "chế độ ăn", "example": "A balanced diet is important.", "pronunciation": "ˈdaɪət", "topic": "health", "lesson_id": 9},
    {"word": "vitamin", "meaning": "vitamin", "example": "Eat fruits for vitamins.", "pronunciation": "ˈvaɪtəmɪn", "topic": "health", "lesson_id": 9},
    {"word": "health", "meaning": "sức khỏe", "example": "Health is wealth.", "pronunciation": "hɛlθ", "topic": "health", "lesson_id": 9},
    {"word": "exercise", "meaning": "bài tập", "example": "I do exercise every day.", "pronunciation": "ˈɛksərsaɪz", "topic": "health", "lesson_id": 9},
    {"word": "rest", "meaning": "nghỉ ngơi", "example": "You need to rest.", "pronunciation": "rɛst", "topic": "health", "lesson_id": 9},
    {"word": "sleep", "meaning": "giấc ngủ", "example": "Get enough sleep.", "pronunciation": "sliːp", "topic": "health", "lesson_id": 9},
    {"word": "stress", "meaning": "căng thẳng", "example": "Too much stress is bad.", "pronunciation": "strɛs", "topic": "health", "lesson_id": 9},
    {"word": "surgery", "meaning": "phẫu thuật", "example": "He needed surgery.", "pronunciation": "ˈsɜːrdʒəri", "topic": "health", "lesson_id": 9},
    {"word": "pharmacy", "meaning": "hiệu thuốc", "example": "I bought medicine at a pharmacy.", "pronunciation": "ˈfɑːrməsi", "topic": "health", "lesson_id": 9},

    # ─── Bài 10: Work & Business (35 từ) ─────────────────────────────────
    {"word": "job", "meaning": "công việc", "example": "She got a new job.", "pronunciation": "dʒɒb", "topic": "work", "lesson_id": 10},
    {"word": "office", "meaning": "văn phòng", "example": "I work in an office.", "pronunciation": "ˈɒfɪs", "topic": "work", "lesson_id": 10},
    {"word": "meeting", "meaning": "cuộc họp", "example": "We have a meeting at 10 AM.", "pronunciation": "ˈmiːtɪŋ", "topic": "work", "lesson_id": 10},
    {"word": "manager", "meaning": "quản lý", "example": "My manager is very supportive.", "pronunciation": "ˈmænɪdʒər", "topic": "work", "lesson_id": 10},
    {"word": "salary", "meaning": "lương", "example": "The salary is competitive.", "pronunciation": "ˈsæləri", "topic": "work", "lesson_id": 10},
    {"word": "contract", "meaning": "hợp đồng", "example": "I signed a contract.", "pronunciation": "ˈkɒntrækt", "topic": "work", "lesson_id": 10},
    {"word": "interview", "meaning": "phỏng vấn", "example": "I have a job interview tomorrow.", "pronunciation": "ˈɪntərvjuː", "topic": "work", "lesson_id": 10},
    {"word": "resume", "meaning": "sơ yếu lý lịch", "example": "Please send your resume.", "pronunciation": "rɪˈzjuːm", "topic": "work", "lesson_id": 10},
    {"word": "promotion", "meaning": "thăng chức", "example": "She got a promotion!", "pronunciation": "prəˈmoʊʃən", "topic": "work", "lesson_id": 10},
    {"word": "experience", "meaning": "kinh nghiệm", "example": "I have 5 years of experience.", "pronunciation": "ɪkˈspɪriəns", "topic": "work", "lesson_id": 10},
    {"word": "skill", "meaning": "kỹ năng", "example": "Communication skills are important.", "pronunciation": "skɪl", "topic": "work", "lesson_id": 10},
    {"word": "team", "meaning": "đội nhóm", "example": "Our team works well together.", "pronunciation": "tiːm", "topic": "work", "lesson_id": 10},
    {"word": "project", "meaning": "dự án", "example": "The project is due next week.", "pronunciation": "ˈprɒdʒɛkt", "topic": "work", "lesson_id": 10},
    {"word": "deadline", "meaning": "hạn chót", "example": "We must meet the deadline.", "pronunciation": "ˈdɛdlaɪn", "topic": "work", "lesson_id": 10},
    {"word": "boss", "meaning": "sếp", "example": "My boss is fair.", "pronunciation": "bɒs", "topic": "work", "lesson_id": 10},
    {"word": "employee", "meaning": "nhân viên", "example": "The company has 100 employees.", "pronunciation": "ɪmˈplɔɪiː", "topic": "work", "lesson_id": 10},
    {"word": "employer", "meaning": "người sử dụng lao động", "example": "The employer offers benefits.", "pronunciation": "ɪmˈplɔɪər", "topic": "work", "lesson_id": 10},
    {"word": "business", "meaning": "kinh doanh", "example": "She runs her own business.", "pronunciation": "ˈbɪznəs", "topic": "work", "lesson_id": 10},
    {"word": "client", "meaning": "khách hàng (dịch vụ)", "example": "The client is happy with our work.", "pronunciation": "ˈklaɪənt", "topic": "work", "lesson_id": 10},
    {"word": "marketing", "meaning": "tiếp thị", "example": "We need a marketing strategy.", "pronunciation": "ˈmɑːrkɪtɪŋ", "topic": "work", "lesson_id": 10},
    {"word": "finance", "meaning": "tài chính", "example": "She works in finance.", "pronunciation": "ˈfaɪnæns", "topic": "work", "lesson_id": 10},
    {"word": "sales", "meaning": "bán hàng", "example": "Sales are increasing.", "pronunciation": "seɪlz", "topic": "work", "lesson_id": 10},
    {"word": "profit", "meaning": "lợi nhuận", "example": "The company made a profit.", "pronunciation": "ˈprɒfɪt", "topic": "work", "lesson_id": 10},
    {"word": "budget", "meaning": "ngân sách", "example": "We have a limited budget.", "pronunciation": "ˈbʌdʒɪt", "topic": "work", "lesson_id": 10},
    {"word": "invest", "meaning": "đầu tư", "example": "We should invest in new technology.", "pronunciation": "ɪnˈvɛst", "topic": "work", "lesson_id": 10},
    {"word": "negotiate", "meaning": "đàm phán", "example": "We need to negotiate the terms.", "pronunciation": "nɪˈɡoʊʃieɪt", "topic": "work", "lesson_id": 10},
    {"word": "strategy", "meaning": "chiến lược", "example": "We need a new strategy.", "pronunciation": "ˈstrætədʒi", "topic": "work", "lesson_id": 10},
    {"word": "task", "meaning": "nhiệm vụ", "example": "Finish each task on time.", "pronunciation": "tæsk", "topic": "work", "lesson_id": 10},
    {"word": "overtime", "meaning": "làm thêm giờ", "example": "I worked overtime yesterday.", "pronunciation": "ˈoʊvərtaɪm", "topic": "work", "lesson_id": 10},
    {"word": "career", "meaning": "sự nghiệp", "example": "She has a successful career.", "pronunciation": "kəˈrɪr", "topic": "work", "lesson_id": 10},
    {"word": "training", "meaning": "đào tạo", "example": "New employees receive training.", "pronunciation": "ˈtreɪnɪŋ", "topic": "work", "lesson_id": 10},
    {"word": "performance", "meaning": "hiệu suất", "example": "His performance is excellent.", "pronunciation": "pərˈfɔːrməns", "topic": "work", "lesson_id": 10},
    {"word": "goal", "meaning": "mục tiêu", "example": "Set clear goals for yourself.", "pronunciation": "ɡoʊl", "topic": "work", "lesson_id": 10},
    {"word": "achievement", "meaning": "thành tựu", "example": "This is a great achievement.", "pronunciation": "əˈtʃiːvmənt", "topic": "work", "lesson_id": 10},
    {"word": "retire", "meaning": "nghỉ hưu", "example": "My father retired at 60.", "pronunciation": "rɪˈtaɪər", "topic": "work", "lesson_id": 10},

    # ─── Bài 11: Education & School (30 từ) ──────────────────────────────
    {"word": "teacher", "meaning": "giáo viên", "example": "The teacher explains clearly.", "pronunciation": "ˈtiːtʃər", "topic": "education", "lesson_id": 11},
    {"word": "student", "meaning": "học sinh, sinh viên", "example": "She is a good student.", "pronunciation": "ˈstjuːdənt", "topic": "education", "lesson_id": 11},
    {"word": "class", "meaning": "lớp học", "example": "We have English class at 8 AM.", "pronunciation": "klæs", "topic": "education", "lesson_id": 11},
    {"word": "school", "meaning": "trường học", "example": "I go to school by bike.", "pronunciation": "skuːl", "topic": "education", "lesson_id": 11},
    {"word": "university", "meaning": "đại học", "example": "She studies at university.", "pronunciation": "ˌjuːnɪˈvɜːrsəti", "topic": "education", "lesson_id": 11},
    {"word": "lesson", "meaning": "bài học", "example": "Today's lesson is about grammar.", "pronunciation": "ˈlɛsən", "topic": "education", "lesson_id": 11},
    {"word": "exam", "meaning": "kỳ thi", "example": "The final exam is next week.", "pronunciation": "ɪɡˈzæm", "topic": "education", "lesson_id": 11},
    {"word": "test", "meaning": "bài kiểm tra", "example": "We have a test on Friday.", "pronunciation": "tɛst", "topic": "education", "lesson_id": 11},
    {"word": "homework", "meaning": "bài tập", "example": "I finished my homework.", "pronunciation": "ˈhoʊmwɜːrk", "topic": "education", "lesson_id": 11},
    {"word": "grade", "meaning": "điểm số", "example": "She got good grades.", "pronunciation": "ɡreɪd", "topic": "education", "lesson_id": 11},
    {"word": "degree", "meaning": "bằng cấp", "example": "He has a bachelor's degree.", "pronunciation": "dɪˈɡriː", "topic": "education", "lesson_id": 11},
    {"word": "library", "meaning": "thư viện", "example": "I study in the library.", "pronunciation": "ˈlaɪbrɛri", "topic": "education", "lesson_id": 11},
    {"word": "dictionary", "meaning": "từ điển", "example": "Look it up in a dictionary.", "pronunciation": "ˈdɪkʃənɛri", "topic": "education", "lesson_id": 11},
    {"word": "knowledge", "meaning": "kiến thức", "example": "Knowledge is power.", "pronunciation": "ˈnɒlɪdʒ", "topic": "education", "lesson_id": 11},
    {"word": "learn", "meaning": "học", "example": "I want to learn English.", "pronunciation": "lɜːrn", "topic": "education", "lesson_id": 11},
    {"word": "teach", "meaning": "dạy", "example": "She teaches math.", "pronunciation": "tiːtʃ", "topic": "education", "lesson_id": 11},
    {"word": "study", "meaning": "học tập", "example": "I need to study harder.", "pronunciation": "ˈstʌdi", "topic": "education", "lesson_id": 11},
    {"word": "understand", "meaning": "hiểu", "example": "Do you understand the lesson?", "pronunciation": "ˌʌndərˈstænd", "topic": "education", "lesson_id": 11},
    {"word": "professor", "meaning": "giáo sư", "example": "The professor is very smart.", "pronunciation": "prəˈfɛsər", "topic": "education", "lesson_id": 11},
    {"word": "semester", "meaning": "học kỳ", "example": "This semester is busy.", "pronunciation": "sɪˈmɛstər", "topic": "education", "lesson_id": 11},
    {"word": "scholarship", "meaning": "học bổng", "example": "She won a scholarship.", "pronunciation": "ˈskɒlərʃɪp", "topic": "education", "lesson_id": 11},
    {"word": "subject", "meaning": "môn học", "example": "My favorite subject is English.", "pronunciation": "ˈsʌbdʒɪkt", "topic": "education", "lesson_id": 11},
    {"word": "course", "meaning": "khóa học", "example": "I registered for the course.", "pronunciation": "kɔːrs", "topic": "education", "lesson_id": 11},
    {"word": "assignment", "meaning": "bài tập lớn", "example": "The assignment is due Friday.", "pronunciation": "əˈsaɪnmənt", "topic": "education", "lesson_id": 11},
    {"word": "campus", "meaning": "khuôn viên trường", "example": "The campus is beautiful.", "pronunciation": "ˈkæmpəs", "topic": "education", "lesson_id": 11},
    {"word": "graduate", "meaning": "tốt nghiệp", "example": "She graduated with honors.", "pronunciation": "ˈɡrædʒueɪt", "topic": "education", "lesson_id": 11},
    {"word": "kindergarten", "meaning": "mẫu giáo", "example": "My son goes to kindergarten.", "pronunciation": "ˈkɪndərɡɑːrtən", "topic": "education", "lesson_id": 11},
    {"word": "principal", "meaning": "hiệu trưởng", "example": "The principal gave a speech.", "pronunciation": "ˈprɪnsəpəl", "topic": "education", "lesson_id": 11},
    {"word": "tuition", "meaning": "học phí", "example": "Tuition is expensive.", "pronunciation": "tuˈɪʃən", "topic": "education", "lesson_id": 11},
    {"word": "education", "meaning": "giáo dục", "example": "Education is important for everyone.", "pronunciation": "ˌɛdʒuˈkeɪʃən", "topic": "education", "lesson_id": 11},

    # ─── Bài 12: Entertainment & Hobbies (25 từ) ─────────────────────────
    {"word": "movie", "meaning": "phim", "example": "Let's watch a movie.", "pronunciation": "ˈmuːvi", "topic": "entertainment", "lesson_id": 12},
    {"word": "music", "meaning": "âm nhạc", "example": "I love listening to music.", "pronunciation": "ˈmjuːzɪk", "topic": "entertainment", "lesson_id": 12},
    {"word": "game", "meaning": "trò chơi", "example": "Children love games.", "pronunciation": "ɡeɪm", "topic": "entertainment", "lesson_id": 12},
    {"word": "hobby", "meaning": "sở thích", "example": "My hobby is reading.", "pronunciation": "ˈhɒbi", "topic": "entertainment", "lesson_id": 12},
    {"word": "book", "meaning": "sách", "example": "I'm reading a good book.", "pronunciation": "bʊk", "topic": "entertainment", "lesson_id": 12},
    {"word": "song", "meaning": "bài hát", "example": "This is my favorite song.", "pronunciation": "sɒŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "dance", "meaning": "nhảy múa", "example": "They dance beautifully.", "pronunciation": "dæns", "topic": "entertainment", "lesson_id": 12},
    {"word": "travel", "meaning": "du lịch", "example": "I love to travel.", "pronunciation": "ˈtrævəl", "topic": "entertainment", "lesson_id": 12},
    {"word": "photography", "meaning": "nhiếp ảnh", "example": "Photography is my passion.", "pronunciation": "fəˈtɒɡrəfi", "topic": "entertainment", "lesson_id": 12},
    {"word": "painting", "meaning": "hội họa", "example": "She enjoys painting.", "pronunciation": "ˈpeɪntɪŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "concert", "meaning": "buổi hòa nhạc", "example": "The concert was amazing!", "pronunciation": "ˈkɒnsɜːrt", "topic": "entertainment", "lesson_id": 12},
    {"word": "theater", "meaning": "nhà hát", "example": "We went to the theater.", "pronunciation": "ˈθɪətər", "topic": "entertainment", "lesson_id": 12},
    {"word": "festival", "meaning": "lễ hội", "example": "The festival is colorful.", "pronunciation": "ˈfɛstɪvəl", "topic": "entertainment", "lesson_id": 12},
    {"word": "garden", "meaning": "khu vườn", "example": "She has a beautiful garden.", "pronunciation": "ˈɡɑːrdən", "topic": "entertainment", "lesson_id": 12},
    {"word": "cooking", "meaning": "nấu ăn", "example": "I enjoy cooking.", "pronunciation": "ˈkʊkɪŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "reading", "meaning": "đọc sách", "example": "Reading is relaxing.", "pronunciation": "ˈriːdɪŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "fishing", "meaning": "câu cá", "example": "He goes fishing on weekends.", "pronunciation": "ˈfɪʃɪŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "camping", "meaning": "cắm trại", "example": "We went camping last weekend.", "pronunciation": "ˈkæmpɪŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "swimming", "meaning": "bơi lội", "example": "Swimming is great exercise.", "pronunciation": "ˈswɪmɪŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "cycling", "meaning": "đạp xe", "example": "Cycling is fun.", "pronunciation": "ˈsaɪklɪŋ", "topic": "entertainment", "lesson_id": 12},
    {"word": "karaoke", "meaning": "hát karaoke", "example": "Let's sing karaoke!", "pronunciation": "ˌkɛriˈoʊki", "topic": "entertainment", "lesson_id": 12},
    {"word": "comedy", "meaning": "hài kịch", "example": "I love comedy shows.", "pronunciation": "ˈkɒmədi", "topic": "entertainment", "lesson_id": 12},
    {"word": "relaxation", "meaning": "sự thư giãn", "example": "I need some relaxation.", "pronunciation": "ˌriːlækˈseɪʃən", "topic": "entertainment", "lesson_id": 12},
    {"word": "entertainment", "meaning": "giải trí", "example": "The city offers many entertainment options.", "pronunciation": "ˌɛntərˈteɪnmənt", "topic": "entertainment", "lesson_id": 12},
    {"word": "vacation", "meaning": "kỳ nghỉ", "example": "We went on a summer vacation.", "pronunciation": "vəˈkeɪʃən", "topic": "entertainment", "lesson_id": 12},

    # ─── Bài 13: Technology & Internet (30 từ) ──────────────────────────
    {"word": "computer", "meaning": "máy tính", "example": "I use a computer for work.", "pronunciation": "kəmˈpjuːtər", "topic": "technology", "lesson_id": 13},
    {"word": "internet", "meaning": "internet", "example": "The internet connects the world.", "pronunciation": "ˈɪntərnɛt", "topic": "technology", "lesson_id": 13},
    {"word": "website", "meaning": "trang web", "example": "I created my own website.", "pronunciation": "ˈwɛbsaɪt", "topic": "technology", "lesson_id": 13},
    {"word": "email", "meaning": "thư điện tử", "example": "Check your email.", "pronunciation": "ˈiːmeɪl", "topic": "technology", "lesson_id": 13},
    {"word": "download", "meaning": "tải xuống", "example": "Download the app now.", "pronunciation": "ˈdaʊnloʊd", "topic": "technology", "lesson_id": 13},
    {"word": "upload", "meaning": "tải lên", "example": "Upload your photos here.", "pronunciation": "ˈʌploʊd", "topic": "technology", "lesson_id": 13},
    {"word": "password", "meaning": "mật khẩu", "example": "Choose a strong password.", "pronunciation": "ˈpæswɜːrd", "topic": "technology", "lesson_id": 13},
    {"word": "screen", "meaning": "màn hình", "example": "The screen is bright.", "pronunciation": "skriːn", "topic": "technology", "lesson_id": 13},
    {"word": "keyboard", "meaning": "bàn phím", "example": "Clean your keyboard.", "pronunciation": "ˈkiːbɔːrd", "topic": "technology", "lesson_id": 13},
    {"word": "mouse", "meaning": "chuột (máy tính)", "example": "Move the mouse to click.", "pronunciation": "maʊs", "topic": "technology", "lesson_id": 13},
    {"word": "smartphone", "meaning": "điện thoại thông minh", "example": "Everyone has a smartphone.", "pronunciation": "ˈsmɑːrtfoʊn", "topic": "technology", "lesson_id": 13},
    {"word": "software", "meaning": "phần mềm", "example": "Install the software first.", "pronunciation": "ˈsɒftwɛr", "topic": "technology", "lesson_id": 13},
    {"word": "hardware", "meaning": "phần cứng", "example": "The hardware needs upgrading.", "pronunciation": "ˈhɑːrdwɛr", "topic": "technology", "lesson_id": 13},
    {"word": "network", "meaning": "mạng", "example": "The network is down.", "pronunciation": "ˈnɛtwɜːrk", "topic": "technology", "lesson_id": 13},
    {"word": "data", "meaning": "dữ liệu", "example": "Back up your data.", "pronunciation": "ˈdeɪtə", "topic": "technology", "lesson_id": 13},
    {"word": "cloud", "meaning": "đám mây (lưu trữ)", "example": "Store files on the cloud.", "pronunciation": "klaʊd", "topic": "technology", "lesson_id": 13},
    {"word": "security", "meaning": "bảo mật", "example": "Online security is important.", "pronunciation": "sɪˈkjʊrɪti", "topic": "technology", "lesson_id": 13},
    {"word": "virus", "meaning": "virus (máy tính)", "example": "My computer got a virus.", "pronunciation": "ˈvaɪrəs", "topic": "technology", "lesson_id": 13},
    {"word": "application", "meaning": "ứng dụng", "example": "This app is very useful.", "pronunciation": "ˌæplɪˈkeɪʃən", "topic": "technology", "lesson_id": 13},
    {"word": "digital", "meaning": "kỹ thuật số", "example": "The world is becoming digital.", "pronunciation": "ˈdɪdʒɪtəl", "topic": "technology", "lesson_id": 13},
    {"word": "technology", "meaning": "công nghệ", "example": "Technology changes fast.", "pronunciation": "tɛkˈnɒlədʒi", "topic": "technology", "lesson_id": 13},
    {"word": "innovation", "meaning": "đổi mới sáng tạo", "example": "Innovation drives progress.", "pronunciation": "ˌɪnəˈveɪʃən", "topic": "technology", "lesson_id": 13},
    {"word": "device", "meaning": "thiết bị", "example": "Turn off your devices.", "pronunciation": "dɪˈvaɪs", "topic": "technology", "lesson_id": 13},
    {"word": "wireless", "meaning": "không dây", "example": "The wireless connection is fast.", "pronunciation": "ˈwaɪrləs", "topic": "technology", "lesson_id": 13},
    {"word": "robot", "meaning": "người máy", "example": "Robots help in factories.", "pronunciation": "ˈroʊbɒt", "topic": "technology", "lesson_id": 13},
    {"word": "artificial", "meaning": "nhân tạo", "example": "Artificial intelligence is advancing.", "pronunciation": "ˌɑːrtɪˈfɪʃəl", "topic": "technology", "lesson_id": 13},
    {"word": "database", "meaning": "cơ sở dữ liệu", "example": "The data is stored in a database.", "pronunciation": "ˈdeɪtəbeɪs", "topic": "technology", "lesson_id": 13},
    {"word": "server", "meaning": "máy chủ", "example": "The server is down for maintenance.", "pronunciation": "ˈsɜːrvər", "topic": "technology", "lesson_id": 13},
    {"word": "algorithm", "meaning": "thuật toán", "example": "The algorithm finds patterns.", "pronunciation": "ˈælɡərɪðəm", "topic": "technology", "lesson_id": 13},
    {"word": "programming", "meaning": "lập trình", "example": "I study computer programming.", "pronunciation": "ˈproʊɡræmɪŋ", "topic": "technology", "lesson_id": 13},

    # ─── Bài 14: Emotions & Feelings (25 từ) ─────────────────────────────
    {"word": "happy", "meaning": "vui vẻ", "example": "I'm happy to see you!", "pronunciation": "ˈhæpi", "topic": "emotions", "lesson_id": 14},
    {"word": "sad", "meaning": "buồn", "example": "The movie made me sad.", "pronunciation": "sæd", "topic": "emotions", "lesson_id": 14},
    {"word": "angry", "meaning": "tức giận", "example": "Don't be angry.", "pronunciation": "ˈæŋɡri", "topic": "emotions", "lesson_id": 14},
    {"word": "excited", "meaning": "hào hứng", "example": "I'm excited about the trip!", "pronunciation": "ɪkˈsaɪtɪd", "topic": "emotions", "lesson_id": 14},
    {"word": "nervous", "meaning": "lo lắng", "example": "I feel nervous before exams.", "pronunciation": "ˈnɜːrvəs", "topic": "emotions", "lesson_id": 14},
    {"word": "scared", "meaning": "sợ hãi", "example": "I'm scared of snakes.", "pronunciation": "skɛrd", "topic": "emotions", "lesson_id": 14},
    {"word": "surprised", "meaning": "ngạc nhiên", "example": "I was surprised by the news.", "pronunciation": "sərˈpraɪzd", "topic": "emotions", "lesson_id": 14},
    {"word": "tired", "meaning": "mệt", "example": "I'm tired after work.", "pronunciation": "ˈtaɪərd", "topic": "emotions", "lesson_id": 14},
    {"word": "bored", "meaning": "chán", "example": "The lecture was boring.", "pronunciation": "bɔːrd", "topic": "emotions", "lesson_id": 14},
    {"word": "confused", "meaning": "bối rối", "example": "I'm confused about the instructions.", "pronunciation": "kənˈfjuːzd", "topic": "emotions", "lesson_id": 14},
    {"word": "proud", "meaning": "tự hào", "example": "I'm proud of my achievements.", "pronunciation": "praʊd", "topic": "emotions", "lesson_id": 14},
    {"word": "grateful", "meaning": "biết ơn", "example": "I'm grateful for your help.", "pronunciation": "ˈɡreɪtfəl", "topic": "emotions", "lesson_id": 14},
    {"word": "lonely", "meaning": "cô đơn", "example": "Sometimes I feel lonely.", "pronunciation": "ˈloʊnli", "topic": "emotions", "lesson_id": 14},
    {"word": "jealous", "meaning": "ghen tị", "example": "Don't be jealous of others.", "pronunciation": "ˈdʒɛləs", "topic": "emotions", "lesson_id": 14},
    {"word": "embarrassed", "meaning": "xấu hổ", "example": "I was embarrassed by my mistake.", "pronunciation": "ɪmˈbɛrəst", "topic": "emotions", "lesson_id": 14},
    {"word": "disappointed", "meaning": "thất vọng", "example": "I was disappointed with the result.", "pronunciation": "ˌdɪsəˈpɔɪntɪd", "topic": "emotions", "lesson_id": 14},
    {"word": "anxious", "meaning": "lo âu", "example": "She feels anxious about the future.", "pronunciation": "ˈæŋkʃəs", "topic": "emotions", "lesson_id": 14},
    {"word": "calm", "meaning": "bình tĩnh", "example": "Stay calm and relax.", "pronunciation": "kɑːm", "topic": "emotions", "lesson_id": 14},
    {"word": "love", "meaning": "yêu thương", "example": "I love my family.", "pronunciation": "lʌv", "topic": "emotions", "lesson_id": 14},
    {"word": "hate", "meaning": "ghét", "example": "I hate getting up early.", "pronunciation": "heɪt", "topic": "emotions", "lesson_id": 14},
    {"word": "hope", "meaning": "hy vọng", "example": "I hope to pass the exam.", "pronunciation": "hoʊp", "topic": "emotions", "lesson_id": 14},
    {"word": "worry", "meaning": "lo lắng", "example": "Don't worry too much.", "pronunciation": "ˈwʌri", "topic": "emotions", "lesson_id": 14},
    {"word": "regret", "meaning": "hối hận", "example": "I regret my decision.", "pronunciation": "rɪˈɡrɛt", "topic": "emotions", "lesson_id": 14},
    {"word": "confidence", "meaning": "sự tự tin", "example": "Speak with confidence.", "pronunciation": "ˈkɒnfɪdəns", "topic": "emotions", "lesson_id": 14},
    {"word": "emotion", "meaning": "cảm xúc", "example": "She showed a lot of emotion.", "pronunciation": "ɪˈmoʊʃən", "topic": "emotions", "lesson_id": 14},

    # ─── Bài 15: Society & Culture (30 từ) ────────────────────────────────
    {"word": "culture", "meaning": "văn hóa", "example": "Vietnam has a rich culture.", "pronunciation": "ˈkʌltʃər", "topic": "society", "lesson_id": 15},
    {"word": "tradition", "meaning": "truyền thống", "example": "Tet is a traditional holiday.", "pronunciation": "trəˈdɪʃən", "topic": "society", "lesson_id": 15},
    {"word": "festival", "meaning": "lễ hội", "example": "The Mid-Autumn Festival is fun.", "pronunciation": "ˈfɛstɪvəl", "topic": "society", "lesson_id": 15},
    {"word": "government", "meaning": "chính phủ", "example": "The government makes laws.", "pronunciation": "ˈɡʌvərnmənt", "topic": "society", "lesson_id": 15},
    {"word": "society", "meaning": "xã hội", "example": "We live in a modern society.", "pronunciation": "səˈsaɪəti", "topic": "society", "lesson_id": 15},
    {"word": "community", "meaning": "cộng đồng", "example": "The community helps each other.", "pronunciation": "kəˈmjuːnəti", "topic": "society", "lesson_id": 15},
    {"word": "people", "meaning": "con người, dân tộc", "example": "The Vietnamese people are friendly.", "pronunciation": "ˈpiːpəl", "topic": "society", "lesson_id": 15},
    {"word": "country", "meaning": "đất nước", "example": "Vietnam is a beautiful country.", "pronunciation": "ˈkʌntri", "topic": "society", "lesson_id": 15},
    {"word": "city", "meaning": "thành phố", "example": "Ho Chi Minh City is busy.", "pronunciation": "ˈsɪti", "topic": "society", "lesson_id": 15},
    {"word": "village", "meaning": "làng quê", "example": "My grandmother lives in a village.", "pronunciation": "ˈvɪlɪdʒ", "topic": "society", "lesson_id": 15},
    {"word": "law", "meaning": "luật pháp", "example": "Everyone must follow the law.", "pronunciation": "lɔː", "topic": "society", "lesson_id": 15},
    {"word": "right", "meaning": "quyền", "example": "Everyone has basic human rights.", "pronunciation": "raɪt", "topic": "society", "lesson_id": 15},
    {"word": "duty", "meaning": "nghĩa vụ", "example": "It's your duty to vote.", "pronunciation": "ˈduːti", "topic": "society", "lesson_id": 15},
    {"word": "volunteer", "meaning": "tình nguyện viên", "example": "She works as a volunteer.", "pronunciation": "ˌvɒlənˈtɪr", "topic": "society", "lesson_id": 15},
    {"word": "charity", "meaning": "từ thiện", "example": "They donated to charity.", "pronunciation": "ˈtʃærɪti", "topic": "society", "lesson_id": 15},
    {"word": "education", "meaning": "giáo dục", "example": "Education is key to development.", "pronunciation": "ˌɛdʒuˈkeɪʃən", "topic": "society", "lesson_id": 15},
    {"word": "environment", "meaning": "môi trường", "example": "Protect the environment.", "pronunciation": "ɪnˈvaɪrənmənt", "topic": "society", "lesson_id": 15},
    {"word": "pollution", "meaning": "ô nhiễm", "example": "Air pollution is a serious problem.", "pronunciation": "pəˈluːʃən", "topic": "society", "lesson_id": 15},
    {"word": "equality", "meaning": "bình đẳng", "example": "Everyone deserves equality.", "pronunciation": "ɪˈkwɒləti", "topic": "society", "lesson_id": 15},
    {"word": "freedom", "meaning": "tự do", "example": "Freedom is a basic right.", "pronunciation": "ˈfriːdəm", "topic": "society", "lesson_id": 15},
    {"word": "peace", "meaning": "hòa bình", "example": "We all want peace.", "pronunciation": "piːs", "topic": "society", "lesson_id": 15},
    {"word": "religion", "meaning": "tôn giáo", "example": "Freedom of religion is important.", "pronunciation": "rɪˈlɪdʒən", "topic": "society", "lesson_id": 15},
    {"word": "language", "meaning": "ngôn ngữ", "example": "English is a global language.", "pronunciation": "ˈlæŋɡwɪdʒ", "topic": "society", "lesson_id": 15},
    {"word": "history", "meaning": "lịch sử", "example": "I love studying history.", "pronunciation": "ˈhɪstəri", "topic": "society", "lesson_id": 15},
    {"word": "art", "meaning": "nghệ thuật", "example": "Art is a form of expression.", "pronunciation": "ɑːrt", "topic": "society", "lesson_id": 15},
    {"word": "media", "meaning": "truyền thông", "example": "Social media connects people.", "pronunciation": "ˈmiːdiə", "topic": "society", "lesson_id": 15},
    {"word": "news", "meaning": "tin tức", "example": "I watch the news every day.", "pronunciation": "njuːz", "topic": "society", "lesson_id": 15},
    {"word": "celebrate", "meaning": "kỷ niệm, ăn mừng", "example": "We celebrate Tet every year.", "pronunciation": "ˈsɛlɪbreɪt", "topic": "society", "lesson_id": 15},
    {"word": "respect", "meaning": "tôn trọng", "example": "Respect your elders.", "pronunciation": "rɪˈspɛkt", "topic": "society", "lesson_id": 15},
    {"word": "globalization", "meaning": "toàn cầu hóa", "example": "Globalization affects everyone.", "pronunciation": "ˌɡloʊbəlaɪˈzeɪʃən", "topic": "society", "lesson_id": 15},
]
