import 'package:flutter/foundation.dart';

import '../models/quiz_category.dart';
import '../models/quiz_result.dart';
import '../services/quiz_service.dart';

class QuizProvider extends ChangeNotifier {
  final QuizService _service;

  List<QuizCategory> _categories = [];
  List<Map<String, dynamic>> _currentQuestions = [];
  QuizResult? _lastResult;
  List<QuizResult> _history = [];
  bool _isLoading = false;
  String? _errorMessage;
  String _selectedTopic = 'all';

  List<QuizCategory> get categories => _categories;
  List<Map<String, dynamic>> get currentQuestions => _currentQuestions;
  QuizResult? get lastResult => _lastResult;
  List<QuizResult> get history => _history;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;
  String get selectedTopic => _selectedTopic;

  QuizProvider(this._service);

  Future<void> fetchCategories() async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _categories = await _service.getCategories();
    } catch (e) {
      _categories = [];
      _errorMessage = 'Không thể tải danh mục quiz.';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  /// Set questions generated by AI directly (skip backend quiz generation).
  void setAIQuestions(List<Map<String, dynamic>> questions) {
    _currentQuestions = questions;
    _errorMessage = null;
    notifyListeners();
  }

  Future<void> generateQuiz({int count = 5, String? topic, String? skillType}) async {
    _isLoading = true;
    _errorMessage = null;
    _currentQuestions = [];
    if (topic != null) {
      _selectedTopic = topic;
    }
    notifyListeners();

    try {
      _currentQuestions = await _service.generateQuiz(
        count: count,
        topic: _selectedTopic,
        skillType: skillType,
      );
    } catch (e) {
      _errorMessage = 'Không thể tạo bài quiz cho chủ đề này.';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> submitQuiz({
    required String quizType,
    required List<Map<String, dynamic>> answers,
    String? topic,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _lastResult = await _service.submitQuiz(
        quizType: quizType,
        answers: answers,
        topic: topic ?? _selectedTopic,
      );
    } catch (e) {
      final correct = answers.where((a) => a['is_correct'] == true).length;
      _lastResult = QuizResult(
        id: 'local_${DateTime.now().millisecondsSinceEpoch}',
        quizType: quizType,
        topic: topic ?? _selectedTopic,
        totalQuestions: answers.length,
        correctAnswers: correct,
        scorePercent: answers.isNotEmpty
            ? (correct / answers.length * 100).toDouble()
            : 0,
        details: answers,
        completedAt: DateTime.now(),
      );
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  int _historyPage = 0;
  bool _hasMoreHistory = true;
  bool get hasMoreHistory => _hasMoreHistory;

  Future<void> fetchHistory({bool loadMore = false}) async {
    if (loadMore) {
      if (!_hasMoreHistory || _isLoading) return;
      _historyPage++;
    } else {
      _historyPage = 1;
      _hasMoreHistory = true;
    }
    _isLoading = true;
    if (!loadMore) _errorMessage = null;
    notifyListeners();

    try {
      final result = await _service.getHistory(page: _historyPage, limit: 20);
      final items = result['items'] as List<QuizResult>;
      if (loadMore) {
        _history.addAll(items);
      } else {
        _history = items;
      }
      _hasMoreHistory = items.length >= 20;
    } catch (e) {
      if (!loadMore) _errorMessage = 'Không thể tải lịch sử quiz.';
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  void setTopic(String topic) {
    _selectedTopic = topic;
    notifyListeners();
  }
}
