"""initial

Revision ID: 96087349788c
Revises: 
Create Date: 2026-07-07 22:01:22.775564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96087349788c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_quiz_user_completed', 'quiz_results', ['user_id', 'completed_at'], unique=False)
    op.create_index('idx_quiz_user_type', 'quiz_results', ['user_id', 'quiz_type'], unique=False)
    op.create_index('idx_activity_date', 'user_daily_activities', ['activity_date'], unique=False)
    op.create_index('idx_activity_user_date', 'user_daily_activities', ['user_id', 'activity_date'], unique=True)
    op.create_index('idx_vocab_review_count', 'vocabularies', ['review_count'], unique=False)
    op.create_index('idx_vocab_user_created', 'vocabularies', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_vocab_user_review', 'vocabularies', ['user_id', 'next_review_date'], unique=False)
    op.create_index('idx_vocab_user_topic', 'vocabularies', ['user_id', 'topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vocab_user_topic', table_name='vocabularies')
    op.drop_index('idx_vocab_user_review', table_name='vocabularies')
    op.drop_index('idx_vocab_user_created', table_name='vocabularies')
    op.drop_index('idx_vocab_review_count', table_name='vocabularies')
    op.drop_index('idx_activity_user_date', table_name='user_daily_activities')
    op.drop_index('idx_activity_date', table_name='user_daily_activities')
    op.drop_index('idx_quiz_user_type', table_name='quiz_results')
    op.drop_index('idx_quiz_user_completed', table_name='quiz_results')
    # ### end Alembic commands ###
